name: nams # Network Analysis Made Simple
channels:
  - defaults
  - conda-forge
  - ericmjl
dependencies:
  - python=3.7
  - matplotlib
  - networkx
  - scipy
  - numpy
  - nxviz
  - hiveplot
  - jupyter=1.0.0
  - jupyterlab=2.2.6
  - ipykernel=5.3.4
  - pandas=1.1.1
  - rise
  - python-louvain
  - tqdm
  - ffmpeg
  - nbstripout=0.3.9
  - pygments
  - pip
  - pyprojroot
  - isort
  - black
  - pyjanitor
  - pre-commit
  - tabulate  # used for exporting dataframe as Markdown tables
  - nbconvert=6.0.7
  - nbconvert-utils=0.6
  - pymdown-extensions
  - mkdocs-material
  - mkdocs
  - markdown
